# Generated by Django 2.1.2 on 2018-10-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longtitude', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imgpath', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed', models.CharField(choices=[('EMAIL', 'EMAIL'), ('FACEBOOK', 'FACEBOOK'), ('PHONE', 'PHONE')], default='PHONE', max_length=10)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('course_cat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Course.Category')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='course_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='Course.Course'),
        ),
        migrations.AddField(
            model_name='branch',
            name='course_br',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='Course.Course'),
        ),
    ]
