# Generated by Django 2.1.2 on 2018-10-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='typed',
            new_name='type',
        ),
    ]
