# Generated by Django 2.1.2 on 2018-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20181010_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='course',
        ),
    ]
