# Generated by Django 2.0.9 on 2018-10-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20181029_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[(1, 'EMAIL'), (2, 'FACEBOOK'), (3, 'PHONE')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Course.Category'),
        ),
    ]
